- name: 'DISTRO'
  value: 'node'
- name: 'INSTALL_URL'
  value: 'https://resources.ovirt.org/pub/ovirt-4.4/iso/ovirt-node-ng-installer/4.4.3-2020112920/el8/ovirt-node-ng-installer-4.4.3-2020112920.el8.iso'
- name: 'DISK_SIZE'
  value: '80G'
- name: 'SPARSIFY_BASE'
  value: 'no'
- name: 'BUILD_UPGRADE'
  value: ''
- name: 'BUILD_ENGINE_INSTALLED'
  value: ''
- name: 'BUILD_HOST_INSTALLED'
  value: ''
- name: 'BUILD_HE_INSTALLED'
  value: ''
